### ISSUE TITLE
goup doesn't respect GOPRIVATE

### ISSUE THREAD

**Issue by capnspacehook** [rvflash/goup#2]
I was trying out `goup` today on a module that imports several private git repos. All the standard `go` commands work with my module and my `GOPRIVATE` settings. I explicitly set `GOPRIVATE`, and it appears that the `go` tooling set `GONOPROXY` and `GONOSUMDB` as well for me, as they all point to some private repos. I'm guessing that `goup` will need to read these env vars, as well as look at the `.netrc` file for credentials, as that is the recommended way to specify private git auth last I checked for `go` tools.

**Comment by rvflash** [comment]
Hi Andrew, thanks for the feedback. 

I guess you refer to the error: `... check failed: git: invalid repository: unsecured call to ...`.
Have you try something like that to work around?
```
GOINSECURE="gitlab.example.lan/*/*" goup .
```

It a good idea to simplify the usage of the command, I will try to work on it.

**Comment by rvflash** [comment]
Done in the latest release: v0.3.0.
