### ISSUE TITLE
Switch to go-git/go-git

### ISSUE THREAD

**Issue by klmitch** [rvflash/goup#6]
While investigating `goup` as a potential addition to our CI, I noticed that it uses `src-d/go-git` to discover available versions.  As I was contemplating implementing something similar if I hadn't found `goup`, I was curious about this repository, but when I went to it, there was a notice at the top of its README saying that development had been moved to `go-git/go-git`.  I would advise that `goup` should be updated to use the new `go-git/go-git` library.

**Comment by rvflash** [comment]
Hi Kevin, thanks for the interest. 

Indeed it's true, I will soon change the package to use the new repository.
